### ISSUE TITLE
Additional typing rules

### ISSUE THREAD

**Issue by javathunderman** [javathunderman/zinnia#3]
- Should write down operational semantics at some point
- Currently:
   - Add types to vectors
      - Bit width
      - Slots
- Statically verify comparisons are well typed (no int comparisons with mismatched widths)
- Represent as Calyx std_reg/comb_1d_mem as needed
- Bools -> isomorphic to 1 bit ints

**Comment by javathunderman** [comment]
Items on here should be done, unless there's anything else @fifty-six ? otherwise will close

**Comment by fifty-six** [comment]
Yeah, lgtm.
